# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/topics/caching/
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version  # For debugging
  - pip install poetry
  - poetry install
  - source `poetry env info --path`/bin/activate  # 激活虚拟环境

# test:
#   script:
#     # - python -m unittest discover -s tests -p "test_*.py" -v
#     - pip install tox  # you can also use tox
#     - tox
#   coverage: '/TOTAL.*\s+(\d+%)$/'

run:
  script:
    - poetry build
    # an alternative approach is to install and run:
    - pip install dist/*.whl
    # run the command here
  artifacts:
    paths:
      - dist/*.whl

# pages:
#   script:
#     - pip install sphinx sphinx-rtd-theme
#     - cd doc
#     - make html
#     - mv build/html/ ../public/
#   artifacts:
#     paths:
#       - public
#   rules:
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build:
  stage: build
  script: 
      - poetry config repositories.gitlab "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi"
      # - poetry config http-basic.gitlab gitlab-ci-token "$CI_JOB_TOKEN"
      - poetry publish --build --repository gitlab -u gitlab-ci-token -p $CI_JOB_TOKEN
  environment: production
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
      - pyproject.toml