
name: demo
run-name: ${{github.actor}} running demo
on: 
    workflow_dispatch:
        inputs:
            mode:
                description: 模式
                required: true
                default: dev
                type: choice
                options:
                    - dev
                    - prod
            

jobs:
    dosomething:
        runs-on: ubuntu-latest
        steps:
            - name: print env
              run: env
