
name: demo
run-name: ${{github.actor}} running demo
on: 
    workflow_dispatch:
            

jobs:
    dosomething:
        runs-on: ubuntu-latest
        steps:
            -   name: Cache
                id: cache
                uses: actions/cache@v3.3.2
                with:
                    path: testfile
                    key: ${{ runner.os }}-test
            
            -   name: Touch testfile
                run: touch testfile

            -   name: Print is cache hitted?
                run: echo "Is cache hitted? ${{ steps.cache.outputs.cache-hit }}" 