
name: demo
run-name: ${{github.actor}} running demo
on: 
    workflow_dispatch:
    push:

jobs:
    dosomething:
        runs-on: ubuntu-latest
        steps:
            - name: print env
              run: env