
name: demo
run-name: ${{github.actor}} running demo
on: [push]

jobs:
    dosomething:
        runs-on: ubuntu-latest
        steps:
            - name: print env
              run: |
                  echo ${{ env.SHIT }}

            - name: print env variables
              run: |
                  echo ${{env.SHIT.SHIT_VAR}}

            - name: print vars
              run: |
                echo ${{vars.TEST_VAR}}
        
            - name: print secrets
              run: |
                echo ${{secrets.PYPI_API_TOKEN}}
