name: Lint
run-name: ${{github.actor}} Lint - ${{github.ref_name}}

on: 
  push:
  pull_request:
  workflow_dispatch: # 手动执行测试


jobs:
    
  ruff-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-检出项目
        uses: actions/checkout@v4

      - name: Ruff Check
        uses: jpetrucciani/ruff-check@0.1.0
        with:
            path: async_adbc/**/*.py
            format: "github"
      