
name: Upload Python Package
run-name: ${{github.actor}} is publishing to pypi

on:
    release:
        types: [published]

    workflow_dispatch:
      inputs:
        version:
          description: 'Release version'
          required: true
          type: string

jobs:
    test:
        uses: ./.github/workflows/test.yml

    deploy:
        runs-on: ubuntu-latest
        needs: [test]
        steps:
            - name: checkout
              uses: actions/checkout@v4
            
            - name: Install Poetry-安装poetry
              run: pipx install poetry
            
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.9'
                  cache: 'poetry'
            
            - name: 将Tag版本号填写到toml配置中
              if: ${{github.event.release.tag_name}}
              run: poetry version ${{github.event.release.tag_name}}

            - name: 将version参数更新到toml配置中
              if: ${{github.event.inputs.version}}
              run: poetry version ${{github.event.inputs.version}}
            
            - name: Install dependencies
              run: |
                  poetry install
            - name: Build package
              run:  poetry build
            - name: Publish package
              run: |
                poetry publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}         
          
    docs:
        needs: [deploy]
        uses: ./.github/workflows/docs.yml
        with:
          deploy: true