
name: Upload Python Package
run-name: ${{github.actor}} is publishing to pypi

on:
    release:
        types: [published]

    workflow_dispatch:
jobs:
    deploy:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/master'
        steps:
            - name: checkout
<<<<<<< HEAD
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
=======
              uses: actions/checkout@v4.1.1
            - name: Set up Python
              uses: actions/setup-python@v4.7.1
>>>>>>> 0d6fe74967a289bf7203763f5480698be77e4488
              with:
                  python-version: '3.9'
                  cache: 'pip'
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install build
            - name: Build package
              run: python -m build
            - name: Publish package
              uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
              with:
                user: __token__
                password: ${{ secrets.PYPI_API_TOKEN }}
