
name: test
run-name: ${{github.actor}} running test

on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.9"
          cache: 'poetry'
      - name: Update pip
        run: pip install --upgrade pip
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install

          
