
name: Test-测试
run-name: ${{github.actor}} Test - ${{github.ref_name}}

on: 
  push:
    paths-ignore:
      - ".github/**"
  pull_request:
  workflow_dispatch: # 手动执行测试


jobs:
  testing:
    runs-on: ubuntu-latest

    services:
      avd:
        image: budtmo/docker-android:emulator_11.0
        ports: 
          - 6080:6080
          - 5554:5554
          - 5555:5555
        env:
          EMULATOR_DEVICE: "Samsung Galaxy S10"
          WEB_VNC: true
        options:
          --device /dev/kvm
        
    steps:
      - name: Wait For AVD To Startup-等待模拟器启动
        uses: jakejarvis/wait-action@v0.1.1
        with:
          time: '60s'

      - name: Checkout-检出项目
        uses: actions/checkout@v4

      - name: Install Poetry-安装poetry
        run: pipx install poetry

      - name: Setup Python-安装python环境
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: 'poetry' # 缓存poetry
      
      - name: Update pip
        run: pip install --upgrade pip

      - name: Install 
        run: |
          poetry install
          poetry show
      
      - name: Cache APT Packages
        uses: awalsh128/cache-apt-pkgs-action@v1.3.1
        with:
          packages: adb
          version: 1.0

      
      - name: Setup ADB-安装adb
        run: |
          sudo apt-get install -y adb
          adb version
          adb devices
          adb shell service list

      - name: Run unittest-运行测试
        run: |
          poetry run python -W ignore -m coverage run -m unittest -v
          poetry run coverage report
