
name: Test-测试
run-name: ${{github.actor}} running test

on: 
  push:
  workflow_dispatch: # 手动执行测试


jobs:
  testing:
    runs-on: ubuntu-latest

    services:
      avd:
        image: budtmo/docker-android:emulator_11.0
        ports: 
          - 6080:6080
          - 5554:5554
          - 5555:5555
        env:
          EMULATOR_DEVICE: "Samsung Galaxy S10"
          WEB_VNC: true
        options:
          --device /dev/kvm
        
    steps:
      - name: Wait For AVD To Startup-等待模拟器启动
        uses: jakejarvis/wait-action@v0.1.1
        with:
          time: '120s'

      - name: Checkout-检出项目
        uses: actions/checkout@v4

      - name: Install Poetry-安装poetry
        run: pipx install poetry

      - name: Setup Python-安装python环境
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: 'poetry' # 缓存poetry
      
      - name: Update pip
        run: pip install --upgrade pip

      - name: Install 
        run: |
          poetry install
          poetry show
      
      - name: Setup ADB-安装adb
        run: |
          sudo apt-get install -y adb
          adb version
          adb devices
          adb shell service list
          adb shell pm

      - name: Run unittest-运行测试
        run: |
          poetry run python -W ignore -m coverage run -m unittest -v
          poetry run coverage report

      - name: Lint with Ruff
        run: |
          poetry run ruff --output-format=github .
        continue-on-error: true
      